version: "3.9"

x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.4}
  environment:
    &airflow-common-env
    AIRFLOW_UID: ${AIRFLOW_UID:-1000}
    AIRFLOW_GID: 0
    AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER: 'true'
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
   
  
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
    - /var/run/docker.sock:/var/run/docker.sock # added - gives Airflow access to Docker socket
  user: "0:0" # added - run as root so Airflow can execute docker commands
  depends_on:
    &airflow-common-depends-on
    postgres_airflow:
      condition: service_healthy

networks:
  sparknet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  # --- AIRFLOW INFRASTRUCTURE ---
  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.30.1.14

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "18080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      sparknet:
        ipv4_address: 172.30.1.15

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      sparknet:
        ipv4_address: 172.30.1.16

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      sparknet:
        ipv4_address: 172.30.1.17

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID:-50000}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      sparknet:
        ipv4_address: 172.30.1.18

  # --- SPARK & JUPYTER ---
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-jupyter
    networks:
      sparknet:
        ipv4_address: 172.30.1.13
    ports:
      - "8899:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jars:/opt/spark/jars
      - ./data:/opt/airflow/data
      - ./dags:/opt/airflow/dags # added - so Jupyter can see and run the ETL scripts
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - SPARK_UI_PORT=4040
      - PYSPARK_SUBMIT_ARGS=--jars /opt/spark/jars/* pyspark-shell
      - HADOOP_CONF_DIR=/etc/hadoop   
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
      - PYTHONPATH=/usr/local/spark-3.5.0-bin-hadoop3/python:/usr/local/spark-3.5.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip # added

    user: root
    command: start-notebook.sh --NotebookApp.token=''

  # --- HADOOP CLUSTER ---
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_namenode_rpc-address=hadoop-namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop-namenode:/hadoop/dfs/name
    networks:
      sparknet:
        ipv4_address: 172.30.1.21

  hadoop-datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode1
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_namenode_rpc-address=hadoop-namenode:9000
      - HDFS_CONF_dfs_datanode_hostname=hadoop-datanode1
    ports:
      - "9864:9864"
    volumes:
      - hadoop-datanode1:/hadoop/dfs/data
    networks:
      sparknet:
        ipv4_address: 172.30.1.22
    depends_on:
      - hadoop-namenode

  hadoop-datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode2
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_namenode_rpc-address=hadoop-namenode:9000
      - HDFS_CONF_dfs_datanode_hostname=hadoop-datanode2
    ports:
      - "9865:9864"
    volumes:
      - hadoop-datanode2:/hadoop/dfs/data
    networks:
      sparknet:
        ipv4_address: 172.30.1.23
    depends_on:
      - hadoop-namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - "8088:8088"
    networks:
      sparknet:
        ipv4_address: 172.30.1.24
    depends_on:
      - hadoop-namenode

  hadoop-nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager
    networks:
      sparknet:
        ipv4_address: 172.30.1.25
    depends_on:
      - resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    volumes:
      - ./notebooks:/home/jovyan/work

  hadoop-nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager2
    networks:
      sparknet:
        ipv4_address: 172.30.1.26
    depends_on:
      - resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  postgres-db-volume:
  hadoop-namenode:
  hadoop-datanode1:
  hadoop-datanode2: